require("plugin_config.catppuccin")
require("plugin_config.telescope")
require("plugin_config.nvim-tree")
require("plugin_config.treesitter")
require("plugin_config.comment")
require("plugin_config.lualine")
require("plugin_config.nvim-cmp")
require("plugin_config.mason")
require("plugin_config.lspsaga")
require("plugin_config.lspconfig")
require("plugin_config.none-ls")
require("plugin_config.gitsigns")
require("plugin_config.diffview")
require("plugin_config.nvim-dap") -- must be after mason
