local builtin = require("telescope.builtin")
vim.keymap.set("n", "<leader>ff", function()
	builtin.find_files({ no_ignore = true, hidden = true })
end, {})
vim.keymap.set("n", "<leader>s", function()
	builtin.grep_string({ search = vim.fn.input("Grep > ") })
end)
