require("settings")
require("keymap")
require("plugin.catppuccin")
require("plugin.telescope")
require("plugin.nvim-tree")
require("plugin.treesitter")
require("plugin.lualine")
require("plugin.gitsigns")
require("plugin.nvim-cmp")
-- require("plugin.mason")
-- require("plugin.lspsaga")
require("plugin.lspconfig")
-- require("plugin.none-ls")
-- require("plugin.diffview")
-- require("plugin.nvim-dap") -- must be after mason

