require("core.settings")
require("core.packer")
require("plugin.catppuccin")
require("plugin.telescope")
require("plugin.nvim-tree")
require("plugin.treesitter")
require("plugin.comment")
require("plugin.lualine")
require("plugin.nvim-cmp")
require("plugin.mason")
require("plugin.lspsaga")
require("plugin.lspconfig")
require("plugin.none-ls")
require("plugin.gitsigns")
require("plugin.diffview")
require("plugin.nvim-dap") -- must be after mason

